language: node_js
node_js:
  - "10"
  - "9"
  - "8"
sudo: false
cache: "npm"
before_deploy:
  - npm run build
deploy:
q  - provider: releases
    api_key: $GITHUB_TOKEN
    file: "dist/index.min.js"
    skip_cleanup: true
    on:
      tags: true
